# Generated by Django 3.0.6 on 2020-07-07 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('ide_cargos', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('valor_cargo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('ide_empleado', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('numero_documento', models.CharField(max_length=50)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('ide_cargos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.Cargos')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('ide_periodo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('anual', models.CharField(max_length=50)),
                ('mes', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Vinculacion',
            fields=[
                ('ide_tipovinculacion', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descripciontipo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_Horas',
            fields=[
                ('ide_reportehoras', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('numerohoras', models.IntegerField()),
                ('ide_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.Empleado')),
                ('ide_periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.Periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Parafiscales',
            fields=[
                ('ide_parafiscales', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('ide_tipovinculacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.Tipo_Vinculacion')),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('ide_nomina', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('valorapagar', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('estado', models.CharField(max_length=50)),
                ('ide_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.Empleado')),
                ('ide_periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.Periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Horas_Adicionales',
            fields=[
                ('ide_horasadicionales', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('valor_porhora', models.FloatField()),
                ('estado', models.CharField(max_length=50)),
                ('ide_reportehoras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.Reporte_Horas')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='ide_tipovinculacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.Tipo_Vinculacion'),
        ),
        migrations.CreateModel(
            name='DetalleParafiscal',
            fields=[
                ('ide_detalleparafiscal', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('totalparafiscal', models.FloatField()),
                ('ide_nomina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.Nomina')),
                ('ide_parafiscales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.Parafiscales')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Horas',
            fields=[
                ('ide_detallehoras', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('ide_horasadicionales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.Horas_Adicionales')),
                ('ide_nomina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.Nomina')),
            ],
        ),
    ]
